/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ande.luxury.hotelapp.views;

import com.ande.luxury.hotelapp.entities.Usuario;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.Timer;
/**
 *
 * @author bryanvislaochavez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    
    public Main() {
        initComponents();
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setTitle("Principal - Ande Luxury");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximiza la ventana
    }
    
     public Main(Usuario usuario) {
        initComponents();
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setTitle("Principal - Ande Luxury");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximiza la ventana
        
        lblUser.setText(usuario.getFullName());
        lblRol.setText("----------");
        lblDate.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        lblTime.setText("Hora: --:--:--");
         // Timer para actualizar la hora
        Timer timer = new Timer(1000, e -> {
            String hora = new SimpleDateFormat("HH:mm:ss").format(new Date());
            lblTime.setText("Hora: " + hora);
        });
        timer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        pnlFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInfo = new javax.swing.JMenu();
        jmiInfoProject = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenu();
        jmiGestionarUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        panelMain.setLayout(new javax.swing.OverlayLayout(panelMain));

        jToolBar1.setRollover(true);

        pnlFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rol:");
        pnlFooter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel2.setText("Usuario:");
        pnlFooter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Fecha y Hora:");
        pnlFooter.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        lblUser.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        pnlFooter.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        pnlFooter.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        lblDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        pnlFooter.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        lblTime.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        pnlFooter.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        jToolBar1.add(pnlFooter);

        mnuInfo.setText("Acerca de");

        jmiInfoProject.setText("Acerca");
        jmiInfoProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInfoProjectActionPerformed(evt);
            }
        });
        mnuInfo.add(jmiInfoProject);

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        mnuInfo.add(jmiSalir);

        jMenuBar1.add(mnuInfo);

        jmUsuarios.setText("Usuarios");

        jmiGestionarUsuarios.setText("Gestionar Usuarios");
        jmiGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionarUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiGestionarUsuarios);

        jMenuBar1.add(jmUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiInfoProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInfoProjectActionPerformed
        // TODO add your handling code here:
             About form = new About();
       panelMain.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_jmiInfoProjectActionPerformed

    private void jmiGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionarUsuariosActionPerformed
        // TODO add your handling code here:
        Usuarios_Gestion form = new Usuarios_Gestion();
        panelMain.add(form);
        form.setVisible(true);
        
    }//GEN-LAST:event_jmiGestionarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuItem jmiGestionarUsuarios;
    private javax.swing.JMenuItem jmiInfoProject;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JDesktopPane panelMain;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables
}
