/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ande.luxury.hotelapp.views;

import com.ande.luxury.hotelapp.entities.Rol;
import com.ande.luxury.hotelapp.entities.Usuario;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author bryanvislaochavez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static String userLoguin;
    
    public Main() {
        initComponents();
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setTitle("Principal - Ande Luxury");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximiza la ventana
    }
    
    public Main(Usuario usuario) {
        initComponents();
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setTitle("Principal - Ande Luxury");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximiza la ventana
        String rol = usuario.getRoles().getFirst().getDescription();
        setPermissionAccordingWithRolesByUser(usuario.getRoles());
        lblUser.setText(usuario.getFullName());
        lblRol.setText(rol);
        lblDate.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        lblTime.setText("Hora: --:--:--");
        // Timer para actualizar la hora
        Timer timer = new Timer(1000, e -> {
            String hora = new SimpleDateFormat("HH:mm:ss").format(new Date());
            lblTime.setText("Hora: " + hora);
        });
        timer.start();
        userLoguin = usuario.getDocumentNumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        pnlFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInfo = new javax.swing.JMenu();
        jmiInfoProject = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenu();
        jmiGestionarUsuarios = new javax.swing.JMenuItem();
        jmHabitaciones = new javax.swing.JMenu();
        jmHabitacionServicios = new javax.swing.JMenuItem();
        jmGenTipoHabitacion = new javax.swing.JMenuItem();
        jmGestHabitaciones = new javax.swing.JMenuItem();
        jmReservas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        panelMain.setBackground(new java.awt.Color(102, 102, 102));
        panelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        panelMain.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panelMain.setDesktopManager(null);
        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);
        getContentPane().add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        pnlFooter.setBackground(new java.awt.Color(51, 255, 51));
        pnlFooter.setDoubleBuffered(false);
        pnlFooter.setEnabled(false);

        jLabel1.setText("Rol:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Fecha y Hora:");

        lblUser.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        lblDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        lblTime.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(lblRol)
                .addGap(551, 551, 551)
                .addComponent(jLabel3)
                .addGap(118, 118, 118)
                .addComponent(lblDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(lblRol)
                    .addComponent(lblDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFooter, java.awt.BorderLayout.PAGE_END);
        pnlFooter.getAccessibleContext().setAccessibleParent(pnlFooter);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnuInfo.setText("Acerca de");

        jmiInfoProject.setText("Acerca");
        jmiInfoProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInfoProjectActionPerformed(evt);
            }
        });
        mnuInfo.add(jmiInfoProject);

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        mnuInfo.add(jmiSalir);

        jMenuBar1.add(mnuInfo);

        jmUsuarios.setText("Usuarios");

        jmiGestionarUsuarios.setText("Gestionar Usuarios");
        jmiGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionarUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiGestionarUsuarios);

        jMenuBar1.add(jmUsuarios);

        jmHabitaciones.setText("Habitaciones");

        jmHabitacionServicios.setText("Gestionar Servicios");
        jmHabitacionServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHabitacionServiciosActionPerformed(evt);
            }
        });
        jmHabitaciones.add(jmHabitacionServicios);

        jmGenTipoHabitacion.setText("Gestion Tipo de Habitaciones");
        jmHabitaciones.add(jmGenTipoHabitacion);

        jmGestHabitaciones.setText("Gestionar Habitaciones");
        jmHabitaciones.add(jmGestHabitaciones);

        jMenuBar1.add(jmHabitaciones);

        jmReservas.setText("Reservas");

        jMenuItem1.setText("Reservar Habitacion");
        jmReservas.add(jMenuItem1);

        jMenuItem2.setText("Servicio - Habitación");
        jmReservas.add(jMenuItem2);

        jMenuItem3.setText("Check-out - Habitación");
        jmReservas.add(jMenuItem3);

        jMenuBar1.add(jmReservas);

        jMenu1.setText("Parametros");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiInfoProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInfoProjectActionPerformed
        // TODO add your handling code here:
        About form = new About();
        form.setClosable(true);          // Botón cerrar
        form.setVisible(true);
        panelMain.add(form);
        
    }//GEN-LAST:event_jmiInfoProjectActionPerformed

    private void jmiGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionarUsuariosActionPerformed
        // TODO add your handling code here:
        Usuarios_Gestion form = new Usuarios_Gestion();
           form.setClosable(true);          // Botón cerrar
        // Configurar el comportamiento al cerrar
        form.setVisible(true);
        panelMain.add(form);        
    }//GEN-LAST:event_jmiGestionarUsuariosActionPerformed

    private void jmHabitacionServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHabitacionServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmHabitacionServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem jmGenTipoHabitacion;
    private javax.swing.JMenuItem jmGestHabitaciones;
    private javax.swing.JMenuItem jmHabitacionServicios;
    private javax.swing.JMenu jmHabitaciones;
    private javax.swing.JMenu jmReservas;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuItem jmiGestionarUsuarios;
    private javax.swing.JMenuItem jmiInfoProject;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu mnuInfo;
    private javax.swing.JDesktopPane panelMain;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables

    private void setPermissionAccordingWithRolesByUser(List<Rol> roles) {
        boolean isRoot = roles.stream().filter(x -> x.getCode().equals("ROOT")).count() > 0;
        if (!isRoot) {
            jmUsuarios.setEnabled(false);
            jmUsuarios.setVisible(false);
            
            boolean isAdmin = roles.stream().filter(x -> x.getCode().equals("ADMIN")).count() > 0;
            // is admin
            boolean isRecepcionista = roles.stream().filter(x -> x.getCode().equals("RECEPCIONISTA")).count() > 0;
            boolean isClient = roles.stream().filter(x -> x.getCode().equals("CLIENT")).count() > 0;
            
        }
    }
}
