/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ande.luxury.hotelapp.views;

import com.ande.luxury.hotelapp.entities.HotelRoom;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author bryanvislaochavez
 */
public class Reservas_CheckIn_Detail extends javax.swing.JFrame {

    /**
     * Creates new form Reservas_CheckIn_Detail
     */
    public Reservas_CheckIn_Detail(HotelRoom room) {
        initComponents();
        lblReserva.setText(room.getBookingReference().getUuid());
        lblTotal.setText("S/." + String.valueOf(room.getBookingReference().getTotal()));
        lblDias.setText(String.valueOf(room.getBookingReference().getTotalNights()));
        lblNinos.setText(String.valueOf(room.getBookingReference().getChildrens()));
        lblAdultos.setText(String.valueOf(room.getBookingReference().getAdults()));
        lblHabitacion.setText(String.valueOf(room.getRoomNumber()) + " - " + room.getRoomType().getDescription().toUpperCase());
        lblClient.setText(room.getBookingReference().getDocumentNumber() + " - " + room.getBookingReference().getFullName());
        lblTelefono.setText(room.getBookingReference().getPhone());
        lblEmail.setText(room.getBookingReference().getEmail());
        Date checkIn = room.getBookingReference().getCheckIn();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        lblCheckin.setText(sdf.format(checkIn));
        if (room.getBookingReference().getCheckOut() != null) {
            Date checkOut = room.getBookingReference().getCheckOut();
            lblCheckout.setText(sdf.format(checkOut));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblReserva = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblHabitacion = new javax.swing.JLabel();
        lblClient = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNinos = new javax.swing.JLabel();
        lblAdultos = new javax.swing.JLabel();
        lblCheckin = new javax.swing.JLabel();
        lblCheckout = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Servicios Adicionales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        lblReserva.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblReserva.setText("----------------");
        getContentPane().add(lblReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Habitación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("DOI - Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Niños");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("Adultos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setText("Checkin");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("CheckOut");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setText("Días");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setText("SUBTOTAL");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTotal.setText("----------------");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        lblHabitacion.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblHabitacion.setText("----------------");
        getContentPane().add(lblHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        lblClient.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblClient.setText("----------------");
        getContentPane().add(lblClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEmail.setText("----------------");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTelefono.setText("----------------");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        lblNinos.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblNinos.setText("----------------");
        getContentPane().add(lblNinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lblAdultos.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblAdultos.setText("----------------");
        getContentPane().add(lblAdultos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        lblCheckin.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCheckin.setText("----------------");
        getContentPane().add(lblCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        lblCheckout.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCheckout.setText("----------------");
        getContentPane().add(lblCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        lblDias.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblDias.setText("----------------");
        getContentPane().add(lblDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setText("RESERVA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservas_CheckIn_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservas_CheckIn_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservas_CheckIn_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservas_CheckIn_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservas_CheckIn_Detail(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAdultos;
    private javax.swing.JLabel lblCheckin;
    private javax.swing.JLabel lblCheckout;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHabitacion;
    private javax.swing.JLabel lblNinos;
    private javax.swing.JLabel lblReserva;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
