# If your package.json is in a subdirectory, use this version instead

name: Deploy Hotel Management App with jDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug repository structure
      run: |
        echo "=== Repository Root Contents ==="
        ls -la
        echo ""
        echo "=== Looking for package.json ==="
        find . -name "package.json" -type f
        
    - name: Change to project directory
      run: |
        # If package.json is in a subdirectory, uncomment and modify this:
        # cd your-subdirectory-name
        # Or use working-directory in subsequent steps
        pwd
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        
    # Rest of the steps would need working-directory specified if in subdirectory
    - name: Install Node.js dependencies
      # working-directory: ./your-subdirectory-name  # Uncomment if needed
      run: |
        if [ ! -f "package.json" ]; then
          echo "❌ ERROR: package.json not found"
          exit 1
        fi
        npm install
        
    - name: Deploy with jDeploy
      # working-directory: ./your-subdirectory-name  # Uncomment if needed
      run: jdeploy publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
